version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"